### PR TITLE
Fix naming conflict and variable initialization under Windows

### PR DESCRIPTION
**Pull request by gunchleoc**
- Remove erroneous initialization of WIN32_FIND_DATAA
- Rename CopyFile to CopyAFile and DeleteFile to DeleteAFile to fix naming conflicts

### CODE REVIEW

**Comment by gunchleoc** [comment]
1. I have no idea why we have a name conflict in spite of the namespace - the linker just craps out. So, after a few days of waiting for the compiler, I chose the easy solution.
2. https://github.com/ValyriaTear/ValyriaTear/pull/621 needs to be merged immediately after this branch

**Comment by Bertram25** [comment]
It's a good thing to be out of the way in a any case. We'll always have issue with the big APIs. So I approve that we do this change.

**Comment by Bertram25** [comment]
Once the VT PR requests are fixed, I'll merge both.

**Comment by gunchleoc** [comment]
Feel free to merge this with the associated VT PR first, I can then take care of any merge conflicts in other branches. I think this one is the most important one, because then I can test everything else under Windows too :)

**Comment by Bertram25** [comment]
Merged ! :)

**Pull request merged**
